[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
piston_window = "0.127.0"
piston-float = "1.0.0"
nalgebra = "0.31.4"
rayon = "1.6.1"
gfx_device_gl = "0.16.2"
regex = "1.7.0"
sdl2_gfx = "0.24.0"
